
  - block:
 
    - name: DEBUG -                 🟢 API URL
      debug: 
        var: k8s_apiurl


    - name: DEBUG -                 🟢 API KEY
      debug: 
        var: k8s_apikey


    - name: Mitigate MYSQL Problem
      shell: |
        export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
        oc patch service mysql -n robot-shop --patch '{"spec": {"selector": {"service": "mysql"}}}'
      ignore_errors: yes

    - name: Incrase MYSQL Memory
      shell: |
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
      ignore_errors: yes

    - name: Update GIT Commit
      shell: |
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../installAIManager.log
      ignore_errors: yes
