- name: Scale deployment up, and extend timeout
  community.kubernetes.k8s_scale:
    api_version: v1
    kind: Deployment
    name: ratings
    namespace: robot-shop
    replicas: 0
    wait_timeout: 60